# Generated by Django 5.1 on 2024-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTrimmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_video', models.FileField(upload_to='original_videos/')),
                ('trimmed_video', models.FileField(upload_to='trimmed_videos/')),
            ],
        ),
    ]
