# Generated by Django 5.1 on 2024-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trimming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotrimmed',
            name='original_audio',
            field=models.FileField(default=None, upload_to='original_audio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotrimmed',
            name='trimmed_audio',
            field=models.FileField(default=None, upload_to='trimmed_audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videotrimmed',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
