# Generated by Django 5.1 on 2024-10-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trimming', '0004_remove_videotrimmed_trimmed_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotrimmed',
            name='cover_picture',
            field=models.FileField(default=None, upload_to='cover_picture/'),
            preserve_default=False,
        ),
    ]
