# Generated by Django 5.1 on 2024-10-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trimming', '0005_videotrimmed_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotrimmed',
            name='cover_picture',
            field=models.FileField(blank=True, null=True, upload_to='cover_picture/'),
        ),
    ]
